name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run lint
      - run: pnpm run prettier . --check
      - name: Sets all variables to unit tests
        env:
          VITE_ACCESS_TOKEN: ${{ secrets.VITE_ACCESS_TOKEN }}
          VITE_OAUTH_TOKEN: ${{ secrets.VITE_OAUTH_TOKEN }}
          VITE_SPACE_ID: ${{ vars.VITE_SPACE_ID }}
        run: pnpm run test

      - run: pnpm run build
